# Generated by Django 3.0.7 on 2021-02-21 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190822_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPreferences',
            fields=[
                ('default_report_date', models.CharField(choices=[('DAY_AFTER_LAST_PLUS', 'Day after last report and last date today'), ('TODAY_PLUS', 'Today and last date today'), ('TODAY', 'Always today')], default='TODAY', max_length=128)),
                ('expanded_menu', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
