# Generated by Django 2.2.4 on 2019-10-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_project_is_notification_enabled'),
        ('employees', '0003_auto_20190805_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskActivityType',
            new_name='ActivityType',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='task_activities',
            new_name='activities',
        ),
    ]
