from decimal import Decimal
from enum import Enum


class ReportModelConstants(Enum):
    MAX_DESCRIPTION_LENGTH = 1024
    MAX_DIGITS = 4
    DECIMAL_PLACES = 2
    MAX_WORK_HOURS = Decimal('24.00')
    MIN_WORK_HOURS = Decimal('0.01')
    MAX_WORK_HOURS_DECIMAL_VALUE = Decimal('0.59')


MONTH_NAVIGATION_FORM_MAX_MONTH_VALUE = 12
MONTH_NAVIGATION_FORM_MIN_MONTH_VALUE = 1
MONTH_NAVIGATION_FORM_MAX_YEAR_VALUE = 2099
MONTH_NAVIGATION_FORM_MIN_YEAR_VALUE = 1990
