# Generated by Django 2.2.2 on 2019-07-08 13:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0003_auto_20190506_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEnabledForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DID_NOT_REPORT_FOR_DAYS', 'DID_NOT_REPORT_FOR_DAYS'), ('HAS_LESS_HOURS_IN_WEEK', 'HAS_LESS_HOURS_IN_WEEK'), ('HAS_MORE_HOURS_IN_WEEK', 'HAS_MORE_HOURS_IN_WEEK'), ('HAS_LESS_PERCENTAGE_OF_HOURS_IN_WEEK', 'HAS_LESS_PERCENTAGE_OF_HOURS_IN_WEEK'), ('HAS_MORE_PERCENTAGE_OF_HOURS_IN_WEEK', 'HAS_MORE_PERCENTAGE_OF_HOURS_IN_WEEK'), ('USER_WEEKLY_HOURS', 'USER_WEEKLY_HOURS'), ('HAS_LESS_HOURS_IN_DAY', 'HAS_LESS_HOURS_IN_DAY'), ('HAS_MORE_HOURS_IN_DAY', 'HAS_MORE_HOURS_IN_DAY')], max_length=40)),
                ('is_enabled', models.BooleanField(default=False)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_enabled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DID_NOT_REPORT_FOR_DAYS', 'DID_NOT_REPORT_FOR_DAYS'), ('HAS_LESS_HOURS_IN_WEEK', 'HAS_LESS_HOURS_IN_WEEK'), ('HAS_MORE_HOURS_IN_WEEK', 'HAS_MORE_HOURS_IN_WEEK'), ('HAS_LESS_PERCENTAGE_OF_HOURS_IN_WEEK', 'HAS_LESS_PERCENTAGE_OF_HOURS_IN_WEEK'), ('HAS_MORE_PERCENTAGE_OF_HOURS_IN_WEEK', 'HAS_MORE_PERCENTAGE_OF_HOURS_IN_WEEK'), ('USER_WEEKLY_HOURS', 'USER_WEEKLY_HOURS'), ('HAS_LESS_HOURS_IN_DAY', 'HAS_LESS_HOURS_IN_DAY'), ('HAS_MORE_HOURS_IN_DAY', 'HAS_MORE_HOURS_IN_DAY')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_at', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_project', to='managers.Project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
